server:
  port: 8080
spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: mail-service
          uri: http://mail:8080
          predicates:
            - Path=/api/mail/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: password-management-service
          uri: http://passwd-mgt:8080
          predicates:
            - Path=/api/reset-password/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: account-management-service
          uri: http://account-mgt:8080
          predicates:
            - Path=/api/account/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: family-management-service
          uri: http://family-mgt:8080
          predicates:
            - Path=/api/family/**,/api/family-invitations/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: budget-management-service
          uri: http://budget-mgt:8080
          predicates:
            - Path=/api/budgets/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: mvc
          uri: http://mvc:8080
          predicates:
            - Path=/home/**, /login , /register , /resources/** , /error , /authenticate , /logout , /
          filters:
            - AddRequestHeader=Gateway, true

        - id: mvc_query
          uri: http://mvc:8080
          predicates:
            - Query=logout
          filters:
            - AddRequestHeader=Gateway, true

        - id: adminer
          uri: http://adminer:8080
          predicates:
            - Path=/adminer
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AddRequestHeader=Gateway, true

        - id: zipkin
          uri: http://zipkin:9411
          predicates:
            - Path=/zipkin
          filters:
            - AddRequestHeader=Gateway, true
