management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true
server:
  port: 8080
  ssl:
    enabled: false
    key-alias: 1
    key-store: certificate.p12
    key-store-type: PKCS12
    key-store-password: P@ssw0rd
    trust-store: certificate.p12
    trust-store-password: P@ssw0rd
spring:
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
    discoveryClientEnabled: false
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: false
      enabled: true
      routes:
        - id: mail-service
          uri: http://mail
          predicates:
            - Path=/api/mail/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: password-management-service
          uri: http://password-management
          predicates:
            - Path=/api/reset-password/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: account-management-service
          uri: http://account-management
          predicates:
            - Path=/api/account-mgt/v1/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: family-management-service
          uri: http://family-management
          predicates:
            - Path=/api/family-mgt/v1/families/**, /api/family-mgt/v1/invitations/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: budget-management-service
          uri: http://budget-management
          predicates:
            - Path=/api/budgets/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: mvc
          uri: http://mvc
          predicates:
            - Path=/home/**, /login , /register , /resources/** , /error , /authenticate , /logout , / , /budget/**, /horsee/**
          filters:
            - AddRequestHeader=Gateway, true

        - id: mvc_query
          uri: http://mvc
          predicates:
            - Query=logout
          filters:
            - AddRequestHeader=Gateway, true

        - id: adminer
          uri: http://adminer:8080
          predicates:
            - Path=/adminer
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AddRequestHeader=Gateway, true

        - id: zipkin
          uri: http://zipkin:9411/
          predicates:
            - Path=/zipkin, /zipkin/**
          filters:
            - AddRequestHeader=Gateway, true
