# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m #JVM maximum heap limit
      TERM: dumb

    steps:
    - setup_remote_docker:
        version: 18.05.0-ce
        docker_layer_caching: true
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run:
        command: |
          gradle wrapper --gradle-version=4.8
          chmod +x gradlew
          gradle dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
#----------------------------------------------------------------------------
    - run:
        name: Build and run Unit Tests
        command: |
          ./gradlew build --stacktrace
    - run:
        name: Run Sonar Analysis
        command: |
          ./gradlew sonarqube -Dsonar.login=${SONAR_TOKEN} --stacktrace
    - run:
        name: Build and push mail service
        command: |
          TAG=0.5-$CIRCLE_BUILD_NUM
          if [["$CIRCLE_BRANCH"=="master"]]; then
          docker build -t konradboniecki/budget:mail-$TAG ./webservice-mail
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push konradboniecki/budget:mail-$TAG ;fi