non_master_branch_filter: &non_master_branch_filter
  filters:
    branches:
      only:
        - develop
        - /feature.*/
        - /bugfix.*/
docker_java_11: &docker_java_11
  docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
      - approve_deployment:
          type: approval
          requires:
            - build
          <<: *non_master_branch_filter
      - deploy:
          requires:
            - approve_deployment
      - deploy-to-nexus-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy-to-nexus:
          requires:
            - deploy-to-nexus-approval
jobs:
  build:
    <<: *docker_java_11
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - add_ssh_keys:
          fingerprints:
            - "5f:9d:14:91:16:7c:39:92:67:55:6d:78:65:7e:f4:64"
      - checkout
      - run:
          name: Build and run tests
          command: |
            mvn clean install -s .circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - run:
          name: Build and push docker image
          command: |
            VERSION=$(mvn help:evaluate -s .circleci/settings.xml -Dexpression=project.version -q -DforceStdout)
            TAG=$CIRCLE_PROJECT_REPONAME-$VERSION-$CIRCLE_BUILD_NUM-PR
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              TAG=$CIRCLE_PROJECT_REPONAME-$VERSION
            fi
            if [ "$CIRCLE_BRANCH" == "develop" ]; then
              TAG=$CIRCLE_PROJECT_REPONAME-$VERSION-$CIRCLE_BUILD_NUM
            fi

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t konradboniecki/budget:$TAG .
            docker push konradboniecki/budget:$TAG

            mkdir shared_workspace
            touch shared_workspace/tag.txt
            echo $TAG > shared_workspace/tag.txt
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports/surefire-report.html
      - store_artifacts:
          path: target/site/jacoco/
      - store_artifacts:
          path: target/surefire-reports
      - persist_to_workspace:
          root: ~/repo
          paths:
            - shared_workspace

  deploy-to-nexus:
    <<: *docker_java_11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy artifacts to nexus
          command: |
            mvn deploy -s .circleci/settings.xml -DskipTests=true

  deploy_master:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:08:5f:ce:8e:cf:4f:2f:c4:ad:fe:9f:18:6c:57:51"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy Master Over SSH
          command: |
            cd /home/circleci/repo/shared_workspace
            export LC_GATEWAY_TAG=$(cat tag.txt)
            echo "================ ATTEMPTING TO DEPLOY $LC_GATEWAY_TAG ================"
            ssh -t -o SendEnv=LC_GATEWAY_TAG root@77.55.214.60 'GATEWAY_TAG=$LC_GATEWAY_TAG; unset LC_GATEWAY_TAG; export GATEWAY_TAG; echo "export GATEWAY_TAG=$GATEWAY_TAG" >> ~/.bashrc; docker tag "konradboniecki/budget:$GATEWAY_TAG" "konradboniecki/budget:tmpTag"; docker rmi "konradboniecki/budget:$GATEWAY_TAG"; docker-compose -f /root/budget-operations/deployment/docker-compose.yaml up -d --no-deps gateway; docker rmi "konradboniecki/budget:tmpTag" || true'
          no_output_timeout: 3m
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:08:5f:ce:8e:cf:4f:2f:c4:ad:fe:9f:18:6c:57:51"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy Over SSH
          command: |
            cd /home/circleci/repo/shared_workspace
            export LC_GATEWAY_TAG=$(cat tag.txt)
            echo "================ ATTEMPTING TO DEPLOY $LC_GATEWAY_TAG ================"
            ssh -t -o SendEnv=LC_GATEWAY_TAG root@77.55.214.60 'GATEWAY_TAG=$LC_GATEWAY_TAG; unset LC_GATEWAY_TAG; export GATEWAY_TAG; echo "export GATEWAY_TAG=$GATEWAY_TAG" >> ~/.bashrc; yq w /root/budget-operations/deployment/k8s/gateway.yaml -i "spec.template.spec.containers[0].image" "konradboniecki/budget:$GATEWAY_TAG"'
          no_output_timeout: 3m
